language: node_js
sudo: false

node_js:
  - 8

cache:
  directories:
  - node_modules

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0

install:
  - npm install -g yarn
  - yarn

script:
  - npm run build

